version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Compile and prepare volume
          command: |
            # Compile the code
            mvn compile
            # Create a dummy container with the application data
            docker create -v /app --name appcon alpine:3.4 /bin/true
            # Copy the repo to the temporary volume
            docker cp $PWD appcon:/app
      - run:
          name: Perform ShiftLeft Scan
          command: |
            set +e
            # start an application container using this volume
            docker run --name slscan -e "WORKSPACE=${CIRCLE_REPOSITORY_URL}" --volumes-from appcon shiftleft/sast-scan scan --src /app --out_dir /app/reports
            # Copy the reports
            docker cp slscan:/app/reports reports
      - store_artifacts:
          path: reports
          destination: shiftleft-scan-reports
