name: Main

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8      
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_REPO: "${{ github.repository }}"
        GITHUB_SHA: "${{ github.sha }}"
        GITHUB_REF: "${{ github.ref }}"
        SHIFTLEFT_ORG_ID: "${{ secrets.SHIFTLEFT_ORG_ID }}"
        SHIFTLEFT_ACCESS_TOKEN: "${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}"
        SHIFTLEFT_API_TOKEN: "${{ secrets.SHIFTLEFT_API_TOKEN }}"
    - name: Build, Analyze and run
      run: sh actionanalysis.sh
