name: ShiftLeft Scan

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Upload report
      uses: Anthophila/codeql-action/codeql/upload-sarif@master
      with:
        sarif_file: "testing"
