name: ShiftLeft Scan

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Upload report
      uses: Anthophila/codeql-action/codeql/upload-sarif@master
      with:
        sarif_file: testing/source-report.sarif
    - name: Upload report
      uses: Anthophila/codeql-action/codeql/upload-sarif@master
      with:
        sarif_file: testing/class-report.sarif
