name: ShiftLeft Scan

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn compile org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom
    - name: Perform ShiftLeft Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        output: reports
    - name: Upload report
      uses: Anthophila/codeql-action/codeql/upload-sarif@master
      with:
        sarif_file: "${{ github.workspace }}/reports"
